// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWbqTWBqyOgimZ9hq00B7n1dpfQNx9VJQ',
    appId: '1:782367762659:web:870e3deca7866e39353dd6',
    messagingSenderId: '782367762659',
    projectId: 'agorapoll-cpp',
    authDomain: 'agorapoll-cpp.firebaseapp.com',
    storageBucket: 'agorapoll-cpp.firebasestorage.app',
    measurementId: 'G-L9V1GZ2495',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSp3JueNVGUUKQcuiF4z9zs9Y98BlMzcs',
    appId: '1:782367762659:android:4fc13c76e992d1d5353dd6',
    messagingSenderId: '782367762659',
    projectId: 'agorapoll-cpp',
    storageBucket: 'agorapoll-cpp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDgmZDo7HuUueGXKWQjXw87dUGjEe-6mc',
    appId: '1:782367762659:ios:88c3df8dbdbb8e38353dd6',
    messagingSenderId: '782367762659',
    projectId: 'agorapoll-cpp',
    storageBucket: 'agorapoll-cpp.firebasestorage.app',
    iosBundleId: 'com.example.agoraPoll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDgmZDo7HuUueGXKWQjXw87dUGjEe-6mc',
    appId: '1:782367762659:ios:88c3df8dbdbb8e38353dd6',
    messagingSenderId: '782367762659',
    projectId: 'agorapoll-cpp',
    storageBucket: 'agorapoll-cpp.firebasestorage.app',
    iosBundleId: 'com.example.agoraPoll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWbqTWBqyOgimZ9hq00B7n1dpfQNx9VJQ',
    appId: '1:782367762659:web:be0a6082333f0d5c353dd6',
    messagingSenderId: '782367762659',
    projectId: 'agorapoll-cpp',
    authDomain: 'agorapoll-cpp.firebaseapp.com',
    storageBucket: 'agorapoll-cpp.firebasestorage.app',
    measurementId: 'G-XQ91QQDPES',
  );

}